# Generated by Django 4.2.11 on 2025-05-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicinebatch_medicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicine.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicine.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicine.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicine Batches',
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='medicine_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinebatch'),
            preserve_default=False,
        ),
    ]
