# Generated by Django 4.2.11 on 2025-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medicine_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
